### ISSUE TITLE
请问怎么打开呢

### ISSUE THREAD

**Issue by chr19960719** [chen365409389/CrazyRestaurant#1]

**Comment by JackQChen** [comment]
可以下载源码编译，也可以直接用编译好的程序
[点击下载](https://github.com/chen365409389/CrazyRestaurant/releases/download/1.0/App.zip)
需要使用夜神模拟器打开动物餐厅，然后按Home键开始就可以了，支持离线刷数据

**Comment by johnseed** [comment]
可以直接用微信PC端小程序打开

**Comment by JackQChen** [comment]
嗯，现在微信PC端也可以运行了，把查找窗体那段代码改一下就行了，用Spy++可以查找窗体信息
